version: "3"

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./:/var/www/
        ports:
            - 8877:80
        depends_on:
            - app
        container_name: proj_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www/
        depends_on:
            - db
        container_name: proj_app

    db:
        image: mysql:8.2
        restart: always
        ports:
            - 8855:3306
        volumes:
            - ./tmp/db/:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: lar_1
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        container_name: proj_db
